# Profil local
spring.datasource.url=jdbc:postgresql://localhost:5431/trader_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.docker.compose.enabled=true
spring.docker.compose.file=docker/docker-compose.yml
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Configuration CORS pour l'environnement local
cors.allowed-origins=http://localhost:4200,http://localhost:3000,http://127.0.0.1:4200
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allow-credentials=true
