# Profil local
spring.datasource.url=jdbc:postgresql://localhost:5432/trader_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.docker.compose.enabled=true
spring.docker.compose.file=docker/docker-compose.yml
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG

