@startuml
' Entités principales
class User {
  -id: Long <<PK>>
  -email: String <<UNIQUE>>
  -name: String
  -password: String
}

class Agent {
  -id: Long <<PK>>
  -name: String
  -targetMarket: Markets
  -inputStartTime: String
  -inputEndTime: String
  -frequency: Frequency
  -outputStartTime: String
  -outputEndTime: String
  -trainingStatus: Status
  -tradingScale: TradingScale
  -version : String
  -user: User <<FK>>
}

class Feature {
  -id: Long <<PK>>
  -name: String
  -description: String
}

class ParameterDefinition {
  -id: Long <<PK>>
  -name: String
  -defaultValue: String
  -type: ParameterTypeEnum
  -required: boolean
  -feature: Feature <<FK>>
}

enum ParameterTypeEnum {
  STRING
  NUMBER
  INTEGER
  BOOLEAN
  DATE
}

enum Status {
  PENDING
  IN_PROGRESS
  COMPLETED
  FAILED
  CANCELLED
}

enum TradingScale {
  HOURLY
  DAILY
  WEEKLY
  MONTHLY
}

enum Frequency {
  MIN_1
  MIN_5
  MIN_15
  MIN_30
  HOUR_1
  DAY_1
  WEEK_1
}

enum Markets
{
    "markerts"
}
class AgentFeature {
  -id: Long <<PK>>
  -agent: Agent <<FK>>
  -feature: Feature <<FK>>
}

class ParameterValue {
  -id: Long <<PK>>
  -value: String
  -agentFeature: AgentFeature <<FK>>
  -parameterDefinition: ParameterDefinition <<FK>>
}

class Prediction {
  -id: Long <<PK>>
  -predictionDate: LocalDate
  -predictedData: double[]
  -actualMarket: double[]
  -agent: Agent <<FK>>
}

' Relations entre entités
User "1" -- "*" Agent : possède >
Agent "1" -- "*" AgentFeature : configure >
Agent "1" -- "*" Prediction : génère >
Feature "1" -- "*" AgentFeature : utilisée dans >
Feature "1" -- "*" ParameterDefinition : définit >
AgentFeature "1" -- "*" ParameterValue : contient >
ParameterDefinition "1" -- "*" ParameterValue : instancie >

@enduml